### ISSUE TITLE
Hacktoberfest: Make it easier to install

### ISSUE THREAD

**Issue by tuladhar** [tuladhar/check_bandwidth#2]
# Hacktoberfest:  Make it easier to install

Currently, there's no `Makefile` and way to installation the NRPE plugin. As such, we need to provide users the ability to easily install our plugin. For example:

```
# This should install the plugin to NRPE plugin directory
$ make install

# Vice-versa
$ make uninstall
```

#### References: 
- https://github.com/tuladhar/set-brightness/blob/main/Makefile
- https://support.nagios.com/kb/article/nrpe-agent-and-plugin-explained-612.html

- - -
Stay Safe & Happy Hacking,
Puru

**Comment by jphetphoumy** [comment]
Hi ! I can help on this issue 

Where do you want to install the nrpe plugin ? 

I know that the nagios plugin path can be configured and changed by the user maybe we can allow the user to install the plugin with the following command 

```
make install INSTALL_PATH=/usr/local/nagios/plugins
```

and add a default path in the Makefile like this : 

```
INSTALL_PATH ?= /usr/local/nagios/libexec/
```

to allow a default install with `make install`

**Comment by tuladhar** [comment]
@jphetphoumy That sounds good. Yeah, for most use cases, the default NRPE plugin path should work fine. I've assigned the issue to you.
